[package]
name = "ss_pathfinder_canvas"
version = "0.5.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "A GPU-accelerated vector graphics renderer that works like HTML canvas"
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/pathfinder"
homepage = "https://github.com/servo/pathfinder"
keywords = ["pathfinder", "canvas", "vector", "graphics", "gpu"]

# default-features = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
# font-kit = { version = "0.6", optional = true }

[dependencies.ss_pathfinder_color]
path = "../color"
version = "0.5"

[dependencies.ss_pathfinder_content]
path = "../content"
version = "0.5"

[dependencies.ss_pathfinder_geometry]
path = "../geometry"
version = "0.5"

[dependencies.ss_pathfinder_renderer]
path = "../renderer"
version = "0.5"

# [dependencies.ss_pathfinder_text]
# path = "../text"
# version = "0.5"
# optional = true

# [dependencies.skribo]
# # path = "../skribo"
# version = "0.1"
# optional = true

# [features]
# pf-text = ["ss_pathfinder_text", "skribo", "font-kit"]
