[package]
name = "ss_pathfinder_ui"
version = "0.5.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "A minimal immediate mode UI library for debugging overlays"
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/pathfinder"
homepage = "https://github.com/servo/pathfinder"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.hashbrown]
version = "0.7"
features = ["serde"]

[dependencies.ss_pathfinder_color]
path = "../color"
version = "0.5"

[dependencies.ss_pathfinder_geometry]
path = "../geometry"
version = "0.5"

[dependencies.ss_pathfinder_gpu]
path = "../gpu"
version = "0.5"

[dependencies.ss_pathfinder_resources]
path = "../resources"
version = "0.5"

[dependencies.ss_pathfinder_simd]
path = "../simd"
version = "0.5"
